version: '3.8'
services:
  nest-api:
    container_name: nest-api-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: hls_db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3

volumes:
  postgres:
    name: nest-db
  pgadmin-data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1